env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'airbnb'
  - 'react'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  arrow-body-style: 0
  indent:
    - 1
    - 2
  linebreak-style:
    - 1
    - windows
  quotes:
    - error
    - double
  semi:
    - 1
    - always
  max-len: 0
  no-console: 0
  no-prototype-builtins: 0
  no-unused-vars: 0
  global-require: 0
  react/prefer-stateless-function: 0
  camelcase: 0
