env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'airbnb'
  - 'react'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  arrow-body-style: 0
  import/no-dynamic-require: 0
  import/no-extraneous-dependencies: 1
  import/extensions: 1
  import/prefer-default-export: 1
  import/no-mutable-exports: 1
  indent:
    - 1
    - 2
  linebreak-style: 0
  jsx-a11y/no-noninteractive-element-interactions: 1
  quotes:
    - error
    - double
  semi:
    - 1
    - always
  max-len: 0
  no-console: 0
  no-prototype-builtins: 0
  no-restricted-syntax: 0
  no-unused-vars: 0
  no-use-before-define: 1
  no-confusing-arrow: 1
  global-require: 0
  react/prefer-stateless-function: 0
  camelcase: 0
  operator-linebreak: 0
  no-return-await: 0
  valid-jsdoc:
    - 1
    - prefer:
        return: "returns"
