# Sass lint rules
ignore:
  - node_modules/**/*.scss
  - node_modules/**/*.sass

rules:
  class-name-format: 0
  empty-line-between-blocks: 0
  force-pseudo-nesting: 0
  quotes:
    - 0
    - style: double
  no-css-comments: 0
  no-important: 0
  no-url-domains: 0
  no-url-protocols: 0
  single-line-per-selector: 0
  leading-zero: 0
  no-color-literals:
    - 0
    - allow-rgba: true
  no-ids: 0
  force-attribute-nesting: 0
  no-qualifying-elements:
    - 0
    - allow-element-with-attribute: true
  no-vendor-prefixes: 0
