# Sass lint rules
ignore:
  - node_modules/**/*.scss
  - node_modules/**/*.sass

rules:
  class-name-format: 0
  empty-line-between-blocks: 0
  force-pseudo-nesting: 0
  quotes:
    - 0
    - style: double
  no-css-comments: 0
  no-important: 0
  no-url-domains: 0
  no-url-protocols: 0
  single-line-per-selector: 0
