/**
 * @overview Constants for tara-explorer
 */
export const TARA_UPDATE_DIR = "TARA_UPDATE_DIR";
export const TARA_GET_DIR = "TARA_GET_DIR";
export const EXPLORER_SEND_DIR = "EXPLORER_SEND_DIR";
export const EXPLORER_SELECT_FILE = "EXPLORER_SELECT_FILE";
export const EXPLORER_DESELECT_FILE = "EXPLORER_DESELECT_FILE";

export default {
  TARA_UPDATE_DIR,
  TARA_GET_DIR,
  EXPLORER_SEND_DIR,
  EXPLORER_SELECT_FILE,
  EXPLORER_DESELECT_FILE,
};
