// Generated by CoffeeScript 2.0.0-beta4
(function() {
  // out: ../lib/api.js, sourcemap: true
  var Menu;

  /*
   * @overview Api for context menu
   * @module tara-right-click-menu
   */
  Menu = require("./menu");

  module.exports = {
    /*
     * Create a menu
     * @param {String} name Name of menu
     * @returns {Menu} Tara Menu class
     */
    createMenu: (name) => {
      return new Menu(name);
    }
  };

}).call(this);
