// Generated by CoffeeScript 2.3.0
(function() {
  // out: ../lib/api.js, sourcemap: true
  /*
   * @overview Api for context menu
   * @module tara-right-click-menu
   */
  var Menu;

  Menu = require("./menu");

  module.exports = {
    /*
     * Create a menu
     * @param {String} name Name of menu
     * @returns {Menu} Tara Menu class
     */
    createMenu: function(name) {
      return new Menu(name);
    }
  };

}).call(this);

//# sourceMappingURL=api.js.map
