// Generated by CoffeeScript 2.0.0-beta4
(function() {
  // out: ../lib/index.js, sourcemap: true
  var TARA_CONFIG_DBS, app, join, remote, rimraf;

  /*
   * @overview Contains the entry point for the right click context menu
   * @module tara-right-click-menu
   */
  ({app, remote} = require("electron"));

  ({join} = require("path"));

  rimraf = require("rimraf");

  ({TARA_CONFIG_DBS} = require("../../../renderer/constants"));

  if (typeof app === "undefined") {
    app = remote.app;
  }

  module.exports.main = function(tara) {
    tara.logger.debug("Loaded tara-right-click-menu.");
    return app.on("window-all-closed", function() {
      tara.logger.debug("Removing context menu dbs...");
      // Rm old stuff
      return rimraf.sync(TARA_CONFIG_DBS);
    });
  };

}).call(this);
